apiVersion: v1
kind: Namespace
metadata:
  name: portfolio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio
  namespace: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      imagePullSecrets:
        - name: harbor-pull
      containers:
        - name: portfolio
          image: 10.2.0.101:5000/portfolio/nn-portfolio:0.1.0-e25ce94
          ports:
            - containerPort: 3000
          env:
            - name: HOSTNAME
              value: 0.0.0.0
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio
  namespace: portfolio
spec:
  selector:
    app: portfolio
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: portfolio-vault-auth
  namespace: portfolio
spec:
  method: appRole
  mount: approle
  appRole:
    roleId: 42009452-b827-c155-df94-0fbf3ee7c7b4
    secretRef: portfolio-vault-approle
  vaultConnectionRef: vault-secrets-operator/default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: portfolio-harbor-pull
  namespace: portfolio
spec:
  type: kv-v2
  mount: downops
  path: nn-portfolio
  refreshAfter: 30s
  vaultAuthRef: portfolio-vault-auth
  destination:
    create: true
    name: harbor-pull
    overwrite: true
    type: kubernetes.io/dockerconfigjson
    transformation:
      templates:
        .dockerconfigjson:
          text: |
            {{- $auth := printf "%s:%s" .Secrets.HARBOR_ROBOT_NAME .Secrets.HARBOR_ROBOT_SECRET | b64enc -}}
            {{- $registry := dict "username" .Secrets.HARBOR_ROBOT_NAME "password" .Secrets.HARBOR_ROBOT_SECRET "auth" $auth -}}
            {{- dict "auths" (dict "10.2.0.101:5000" $registry) | toJson -}}
